### ISSUE TITLE
Slow response times in Level Graph Inspector

### ISSUE THREAD

**Issue by Lyntier** [OndrejNepozitek/Edgar-Unity#97] opened 2021-04-21 21:07 UTC
Loving the package so far, but having a small issue with inspector performance.

Tested in fresh project, 2020.3.4f1, v2.0.0 alpha 8 . The Inspector for Level Graphs lags behind by about a third to half a second. 

https://user-images.githubusercontent.com/64606744/115620910-169d6380-a2f6-11eb-9ff8-f14c154b49a3.mp4

---

Other inspectors in the package work fine.

https://user-images.githubusercontent.com/64606744/115620939-1e5d0800-a2f6-11eb-9baf-1536a802d050.mp4

This problem can mostly be avoided by setting up the level graphs as early as possible and only editing the sets from there on, but it's a minor annoyance and I'm still wondering if this is a me-problem.

**Comment by OndrejNepozitek** [comment] 2021-04-21 21:39
Thanks for reporting the problem and for the videos! I think that I also ran into some issues with the inspector but as you said it was just a minor annoyance so I haven't investigated further. I think that something must have changed between the versions of Unity because I haven't seen any problems in Unity 2018 which is the version in which I primarily develop the asset (to make it compatible with older versions).

I'll look into that in the following days.

**Comment by OndrejNepozitek** [comment] 2021-04-25 09:32
This should be fixed in the hotfix build that I just released. It affected only the PRO version of the asset because it was caused by the custom room and connection type dropdowns. If you decide to download the hotfix release, please let me know if it worked.

**Closed by OndrejNepozitek** 2021-04-25 09:32 UTC
Labels: PRO version, bug

**Comment by Lyntier** [comment] 2021-04-25 09:47
Just checked it out, works flawlessly. Thanks for the ridiculously fast response!
